# Generated by Django 4.2.6 on 2025-03-29 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='description',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
