# Generated by Django 4.2.6 on 2025-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_dossier_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='description',
            field=models.TextField(default='Aucune description'),
            preserve_default=False,
        ),
    ]
