# Generated by Django 4.2.6 on 2025-03-29 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dossier_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
