# Generated by Django 4.2.6 on 2025-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dossier_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='description',
            new_name='encrypted_description',
        ),
        migrations.AddField(
            model_name='dossier',
            name='nonce',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='dossier',
            name='tag',
            field=models.BinaryField(default=b''),
        ),
    ]
