# Generated by Django 4.2.6 on 2025-04-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_description_dossier_encrypted_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='encrypted_description',
            new_name='description',
        ),
    ]
